//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashier
    {
        public int idcashiers { get; set; }
        public string id { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
    }
}
