//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int idorderdetails { get; set; }
        public int id { get; set; }
        public sbyte @return { get; set; }
        public sbyte count { get; set; }
        public Nullable<float> discount { get; set; }
        public int categories_idcategories { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
