//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int idtransactions { get; set; }
        public int orderdetails_idorderdetails { get; set; }
        public int cashboxs_idcashboxs { get; set; }
        public int cashiers_idcashiers { get; set; }
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public float totalprice { get; set; }
        public Nullable<float> discount { get; set; }
    }
}
