//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int IdTransaction { get; set; }
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public float TotalPrice { get; set; }
        public Nullable<float> Discount { get; set; }
        public int CashboxId { get; set; }
        public int CashierId { get; set; }
        public int OrderdetailId { get; set; }
    
        public virtual Cashbox Cashbox { get; set; }
        public virtual Cashier Cashier { get; set; }
        public virtual Orderdetail Orderdetail { get; set; }
    }
}
