//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApp.Core.GeneratedModels
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Cashbox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cashbox()
        {
            this.Transactions = new HashSet<Transaction>();
        }

        private bool shouldSerializeShop = true;
        private bool shouldSerializeTransactions = true;

        [JsonProperty(Order = 1)]
        public int IdCashbox { get; set; }
        [JsonProperty(Order = 2)]
        public int Id { get; set; }
        [JsonProperty(Order = 3)]
        public int ShopId { get; set; }

        [JsonProperty(Order = 4)]
        public virtual Shop Shop { get; set; }
        [JsonProperty(Order = 5)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]  
        public virtual ICollection<Transaction> Transactions { get; set; }

        public void SetShouldSerializeShop(bool should)
        {
            shouldSerializeShop = should;
        }

        public void SetShouldSerializeTransactions(bool should)
        {
            shouldSerializeTransactions = should;
        }

        public bool ShouldSerializeShop()
        {
            return shouldSerializeShop;
        }

        public bool ShouldSerializeTransactions()
        {
            return shouldSerializeTransactions;
        }
    }
}
