//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApp.Core.GeneratedModels
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Cashier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cashier()
        {
            this.Transactions = new HashSet<Transaction>();
        }

        private bool shouldSerializeTransactions = true;

        [JsonProperty(Order = 1)]
        public int IdCashier { get; set; }
        [JsonProperty(Order = 2)]
        public string Id { get; set; }
        [JsonProperty(Order = 3)]
        public string Password { get; set; }
        [JsonProperty(Order = 4)]
        public string Name { get; set; }
        [JsonProperty(Order = 5)]
        public string Surname { get; set; }

        [JsonProperty(Order = 6)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }

        public void SetShouldSerializeTransactions(bool should)
        {
            shouldSerializeTransactions = should;
        }

        public bool ShouldSerializeTransactions()
        {
            return shouldSerializeTransactions;
        }

       
    }
}
