//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopWebApp.Core.GeneratedModels
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Cashboxes = new HashSet<Cashbox>();
        }

        private bool shouldSerializeCashboxes = true;

        [JsonProperty(Order = 1)]
        public int IdShop { get; set; }
        [JsonProperty(Order = 2)]
        public string Name { get; set; }
        [JsonProperty(Order = 3)]
        public string Address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonProperty(Order = 4)]
        public virtual ICollection<Cashbox> Cashboxes { get; set; }

        public void SetShouldSerializeCashboxes(bool should)
        {
            shouldSerializeCashboxes = should;
        }
        public bool ShouldSerializeCashboxes()
        {
            return shouldSerializeCashboxes;
        }
    }
}
